version: '3.7'

services:
  neo4j:
    container_name: neo4j-test
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/test
    networks:
      - neo4j-test
    restart: unless-stopped
networks:
  neo4j-test:
